name: Run M2E
on:
schedule:
  - cron: '0 10 * * 1'
jobs:
build:
runs-on: ubuntu-latest
steps:
  - name: Checkout repository
uses: actions/checkout@v2
  - name: Set up Python
uses: actions/setup-python@v2
with:
python-version: 3.11
  - name: Install dependencies
run: |
  python -m pip install --upgrade pip
# Jeśli masz plik requirements.txt z zależnościami, dodaj:
# pip install -r requirements.txt
- name: Run M2E
run: python M2E.py