name: Run M2E
on:
schedule:
  - cron: '30 22 * * 7'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
          - name: Run M2E
            run: python M2E.py

      - name: Upload M2E_games.xlsx as artifact
        uses: actions/upload-artifact@v2
        with:
          name: M2E_games.xlsx
          path: M2E_games.xlsx